### ISSUE TITLE
AttributeError: module 'radiopropa' has no attribute 'HDF5Output'

### ISSUE THREAD

**Issue by AlexKyriacou92** [nu-radio/RadioPropa#15]
Hello,
I've recently installed RadioPropa as per the instructions with ReadMe.md and none of the scripts radio_example work. I get the complaint:
AttributeError: module 'radiopropa' has no attribute 'HDF5Output'

I checked in the file radiopropa.py in my build directory and there's nothing corresponding to HDF5Output, so I suspect that radiopropa.py was not constructed properly when I ran make install. 

I'm not sure where to begin with trying to debug this, so perhaps I could have some help/guidance with one of the authors of RadioPropa. I have included all of the text in the radiopropa.py file in my build directory as radiopropa-py.txt
Perhaps this could be helpful in diagnosing what went wrong. 
[radiopropa-py.txt](https://github.com/nu-radio/RadioPropa/files/7529126/radiopropa-py.txt)

Cheers,
Alex

**Comment by anelles** [comment]
@boboeyen this sounds like something that you can help with best. (Just pinging you to make sure that this pops up.)

**Comment by boboeyen** [comment]
Oh, sorry I saw this so late, @AlexKyriacou92 

Recently Christophe had the same problem and it was due to the fact he had not installed HDF5 itself. It is apparently possible to have h5py en HDFCompass installed for example without having HDF5 itself. In that case radiopropa will not install the HDF5Output module

**Comment by AlexKyriacou92** [comment]
Thanks for your reply boboeyen.
Yes, I was able to solve this issue by installing HDF5 on ubuntu using anaconda, so now the HF4Output module is constructed. Perhaps you could mention this as a dependency of the code?
